[project]
name = "ml-orch-sdk"
version = "0.3.0"
description = "Provide general python tools can be used outside of Cosmos orchestration product"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests>=2.32.3",
]

[tool.uv]
dev-dependencies = [
    "pytest>=8.3.5",
]
